### ISSUE TITLE
Pasteboard write support

### ISSUE THREAD

**Issue by sehrgut** [tobywf/pasteboard#1]
Would writing to the pasteboard be a feature you'd consider adding? It would make this module much simpler to use than calling into PyObjC for that.

**Comment by tobywf** [comment]
Hey, thanks for getting in touch. It's easy, just haven't needed it before. Sorry to leave you waiting, but I need sign-off from my employer to release code.  Should be a formality in this case.

**Comment by tobywf** [comment]
Version 0.2 is uploaded to [PyPI](https://pypi.org/project/pasteboard/), so you can just install it using `pip`. Let me know if it works, so I can close off the issue!

**Comment by sehrgut** [comment]
Thanks! I'll make a test version of sehrgut/pbtool which is what I was originally wanting this for: I'd love to be able to port it to this and not be maintaining pyobjc calls across multiple osx versions myself.
