### ISSUE TITLE
Can't install in Python 3.10

### ISSUE THREAD

**Issue by TheAngel73** [tobywf/pasteboard#14]
Hi Tobywf, first of all a BIG thank you for this very useful library.

I use pasteboard on a few small app to analyze dragged and dropped files, however I'm now switching to Python 3.10 and pip installing your library now throws an error.
Am I doing something wrong? Sorry but I'm fairly new to the Python world, thanks and sorry to bother you!

Angelo

**Comment by tobywf** [comment]
Hi Angelo, I need more info to look into this. What version of `pip` are you using, and what is the error message?

If you have the time and knowledge about Python packaging, please also see issue #7 . You may be able to find some parallels.

One thing I can say is that this package doesn't (yet) provide pre-built wheels for Python 3.10. Generally, for new Python versions, it takes a while for me to add the pre-built wheels - if I do it at all, since I don't support pasteboard.

**Comment by TheAngel73** [comment]
You're right, I was too generic.
I tried to install it in a iMac, running PyCharm in a virtual environment with a bunch of libraries (mainly PyPi6).
Here is what I received (copied and pasted directly from terminal), with Python 3.9.x everything went fine; and sorry, I don't know what PEP 517 means, perhaps I'm doing something wrong.

(venv310) angelo@iMac-di-Angelo Python Projects % pip install pasteboard --no-use-pep517
Collecting pasteboard
  Using cached pasteboard-0.3.3.tar.gz (13 kB)
ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of poetry.core.masonry.api in pyproject.toml
WARNING: You are using pip version 21.1.2; however, version 22.0.3 is available.

Thank you for the answer!

EDIT: Not using the "--no-use-pep517" parameters also throws an error that ends with:
`ERROR: Could not build wheels for pasteboard which use PEP 517 and cannot be installed directly`

**Comment by luckman212** [comment]
@TheAngel73 Now that Homebrew's default Python is 3.10, I am hitting this error. Did you ever find a solution?

**edit:** I found that all I had to do was (re)install `poetry` followed by reinstalling `pasteboard`

```shell
unset PIP_REQUIRE_VIRTUALENV
$(brew --prefix)/bin/pip3 install poetry
$(brew --prefix)/bin/pip3 install pasteboard
```

**Comment by TheAngel73** [comment]
> @TheAngel73 Now that Homebrew's default Python is 3.10, I am hitting this error. Did you ever find a solution?
> 
> **edit:** I found that all I had to do was (re)install `poetry` followed by reinstalling `pasteboard`
> 
> ```shell
> unset PIP_REQUIRE_VIRTUALENV
> $(brew --prefix)/bin/pip3 install poetry
> $(brew --prefix)/bin/pip3 install pasteboard
> ```

Hi @luckman212 and thank you for the solution. I tried quickly installing first poetry and then pasteboard from PyCharm with no success... I'll try later from the terminal.

**Comment by tobywf** [comment]
Thanks to #19 and the v0.4.0 release, we now have wheels for 3.10. As a reminder, pasteboard is basically unmaintained ( #18 ).
