### ISSUE TITLE
No module named 'pasteboard._native'

### ISSUE THREAD

**Issue by N-Demir** [tobywf/pasteboard#17]
Hey there! I tried to install pasteboard with `pip install pasteboard` on python v3.11.2 and macos v13.2.1 and received the following error:
```
Python 3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pasteboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ndemir/engineer/turbo/pyturbo/.venv/lib/python3.11/site-packages/pasteboard/__init__.py", line 10, in <module>
    from ._native import *
ModuleNotFoundError: No module named 'pasteboard._native'
```

**Comment by tobywf** [comment]
Sorry, I have some bad news. I likely won't fix this. I don't really have the time, plus I'm no longer active in the Python ecosystem. An additional problem is that while GitHub graciously provides free runners (great for open source), there are no ARM64 (i.e. M1/M2) runners. This makes it very difficult to build wheels that work on ARM-based Macs.

However, you should be able to build the package from source. The error you got could indicate that building the native module (the Objective-C code in [`pasteboard.m`](https://github.com/tobywf/pasteboard/blob/15afc43f61da52378cc8d0f367030affd4efaf72/src/pasteboard/pasteboard.m) failed. That is an explanation why it couldn't be found. In this case, there would've been an error during `pip install`. It's also possible that Python packaging has changed yet again...

You may find more info in #14 or #15. Good luck! I'll help if I can, but no promises.

**Comment by mindaugasw** [comment]
Hi @N-Demir, were you able to solve the issue?

For me pasteboard successfully installs and works on M1 Mac, Python 3.10.11, macOS 13.0.
But I get the same error as you when trying to use pasteboard in python for Intel Macs (`python3.10-intel64` from `universal2` python build).

I would like to build my app for both M1 and Intel Macs on my M1 Mac. But I get the same error as you when trying to run my app with Intel python, or when running my compiled app on Intel Mac.

**Comment by tobywf** [comment]
Hi @mindaugasw , unfortunately Pasteboard is now effectively unmaintained, please see #18.

If you still want to proceed and use Pasteboard, a possible workaround might be to install the package [from source](https://pip.pypa.io/en/stable/topics/vcs-support/), instead of from PyPI.

**Comment by tobywf** [comment]
Thanks to #19 and the v0.4.0 release, this is hopefully resolved. As a reminder, pasteboard is basically unmaintained ( #18 ).
