### ISSUE TITLE
DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats

### ISSUE THREAD

**Issue by BernardGreenberg** [tobywf/pasteboard#5]
DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats

is issued by pasteboard in all apps calling it from Python 3.8.  This is using version 0.2.0, which is the latest available to pip3 install.  Perhaps that needs upgrade/recompilation.

**Comment by tobywf** [comment]
I'm using `Py_ssize_t` already, but forgot to define `PY_SSIZE_T_CLEAN` - so it should be an easy fix. I'll see if I can get a new version out this week.

**Comment by tobywf** [comment]
Try 0.3.0, should be available on PyPI!

**Comment by BernardGreenberg** [comment]
Works flawlessly, many thanks!  Please close if you wish.
